language: node_js
node_js:
- '4.3'
script:
- npm install
- npm test
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: D1wTb8xSwp6y4jxU3Hd2gOuxKfUdNFDHmf+aEv0fLc1CeJltnRX16GYQd7DBmK9qAtq2dljIr5niRprgv+FtmEWM8C5UqN7kFRRso0AZwMmt88yjj1aF10T8wXerT/bA/oQWhd8fflTGKxUVi/gdKWqdrGKoZ57T7SO8H7LM9afDvY3R7igxbBCd5+L2rvZnaTZ4PY1jpeK+V7udA7ShrgF7X6gNdk7PRWL7KLJbYnzV4IeQCL4BRe8TKjYANiUpKPcmZW99LOokcm9EpL8OVYsQnakArcOeSdrNDM8OTzuJi5y/4B2Hf5WUTSD37r2BnYZhtSzeSeui0gN0m5gsLinmkP0cXVTFm3rA4DL12qTBotn/dhultSx2ojCX5eHrEF/bSZeZ/y2812FORpweb83vtEMYceFPvkuova3eI0+PhnqcnFIHWO8y2tr+sIi3yXErGrkCUCpgqOlbYPwQZv9hhvKCRNg8ifKg08hAk6Gel/v5/OBVhkJ3EY3cDw4+qn5V1JOEoOo1n6S4HUyZfQiBn6xtN93TiUoVjYOsDSSentzZobg56OsM1gGUuemcZHHzSxnmfFZ2h7cgvbmNwB6h1X5tMAVqV+WzVCwlHcQ9sdRYxdRBheMGcq9vBGu8S3BjETRogYOquMseWKx+j/mRn2aLL3TEf59ziHLa/Qw=
  - secure: R8qJcL7qfpPpYlmD/XTlKdSxkct3R5AYdIFtHLqBRXDXffWfHkijSSWuBPNOqIv/0eKibCtM6Ds/OoVpCoVIpCehQc6VFGQxS/ySsSv4bLq12o18vCJUDinB6T2PGomC1IX8teTis2pVwpKeY7Nnce5ESIzDdVAhQC5+jPL9+5ggFYQcoeDdJGL+g6tScaAZAVm6wQUfPYqD1gobwgWO5Vm8QYXtb8em3fYXneKEVN+yDRAfjAnHf+a8kVT0ibehJSTQHG3qyuLsZfu1Xddj2a7BdoCYLxLLtsyzYpQrW/I8++DhRBqMfXyNFl7THHk5gUPK5Xpl8PX6jiW28/F4GKetZS4OfKn35eBbEwq02WWff59jLX7cP7R+xtUhytPmhEiM+TUyPe1jimwCurzvD4NAM072QrI1tS6qGtKzAtL2uCb39RACfVFVjKfiBPO2YrXSk8Lsixh/oGt4aLr9/wJNxU9j2xMHhCiVB7woIQ7ctxfya7MKvQZ8t5sZPUi6ur44LSGD92otFo7jic13zLo6EngBG3WlGL33ph4jkrfyz3gi+qukA+LECfOhR3HA/VCHvKHks7++z+OSC4eYK1zDWT51EMkozvdsq0URcCsfaB3nL/tNDf49PfyQ0noKZu/tunvN6eP9JALGOuji8V8LxZX/S1DEmf50D9M3k+E=
